version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
      - VITE_APP_NAME=MedicoAgenda
      - VITE_APP_VERSION=1.0.0
      - VITE_ENVIRONMENT=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - medicoagenda

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - medicoagenda

volumes:
  node_modules:
  redis_data:

networks:
  medicoagenda:
    driver: bridge